import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LowerHeader from "./components/LowerHeader";
import Footer from "./components/Footer";
import UpperHeader from "./components/UpperHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UpperHeader />
        <LowerHeader />
        <div className="flex justify-end p-3">
        <SignedIn>
          <UserButton/>
        </SignedIn>
        </div>
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  );
}
